version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_pos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432

#  minio:
#    image: minio/minio:latest
#    container_name: minio
#    environment:
#      MINIO_ROOT_USER: "minioadmin"
#      MINIO_ROOT_PASSWORD: "minioadmin"
#    volumes:
#      - ./data:/data
#    ports:
#      - 9000:9000
#      - 9001:9001
#    command: server /data --console-address :9001