spring:
  application:
    name: Point of Sale
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin123
    url: jdbc:postgresql://localhost:5432/db_pos
